modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "echodimension"
version = "1.0.0"
displayName = "Echo Dimension"
authors = "Raktos1030"
description = '''
Echo Dimension - A mod where your past actions haunt the world as playable echoes.
Travel to a dark reflection of the Overworld where your builds, kills, and mined resources
appear as spectral entities waiting to be restored.
'''

[[dependencies.echodimension]]
modId = "neoforge"
type = "required"
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.echodimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"